# Generated by Django 4.1.5 on 2023-01-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("uploaded_on", models.DateTimeField(auto_now=True)),
                ("report", jsonfield.fields.JSONField(blank=True, null=True)),
                ("model_file", models.FileField(upload_to="static/upload/%Y/%m/%d/")),
                ("train_file", models.FileField(upload_to="static/upload/%Y/%m/%d/")),
                ("test_file", models.FileField(upload_to="static/upload/%Y/%m/%d/")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_on"],
            },
        ),
    ]
